# Use root/example as user/password credentials
version: '3.5'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adminpw
      MYSQL_DATABASE: mydbeditor
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd

  lcarsc:
    image: hstubbe/lcarsc:latest
    restart: always
    ports:
      - 3838:3838