# Use root/example as user/password credentials
version: '3.5'

services:

  dbeditor:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coucou
      MYSQL_DATABASE: mydbeditor
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  lcarsc:
    image: hstubbe/recrf:editor
    restart: always
    ports:
      - 3838:3838