proxy:
  title: Test Server
  port: 7070 
  template-path: /templates/test
 
  authentication: simple
  admin-groups: test_admin
  users:
  - name: test_user
    password: test_user
    groups: test_admin
  
  container-backend: docker 
  
  docker:
      internal-networking: true
  
  specs: 
    
  - id: lcarsc
    display-name: LCARSC
    description: This is the LCRAS-C App
    container-image: hstubbe/lcarsc:latest
    container-cmd: ["R", "-e", "lcarsc::run_app(ecrf_dbuser = 'usertest', ecrf_dbpassword = 'usertest', ecrf_dbhost = 'dbtest', ecrf_dbname = 'mydbtest', config_dbuser = 'usertest', config_dbpassword = 'usertest', config_dbhost = 'dbtest', config_dbname = 'mydbtest', confirm_write_db = FALSE, options = list(host = '0.0.0.0', port = 3838))"]
    container-network: sp-net
    access-groups: test_admin

logging:
  file:
    shinyproxy.log

 
