# Use root/example as user/password credentials
version: '3.5'

services:
                              
  shinyproxy:
#    image: openanalytics/shinyproxy:latest
    image: openanalytics/shinyproxy:2.6.1
    ports:
      - 7070:7070
    networks:
      - sp-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role==manager
    volumes:
      - ./application/application_test.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./templates/test/:/templates/test/
    user: ":${DOCKERID}"
    
    
  dbtest:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coucoutest
      MYSQL_DATABASE: mydbtest
      MYSQL_USER: usertest
      MYSQL_PASSWORD: usertest
    volumes:
      - ./mariadb/data/:/var/lib/mysql
      - ./mariadb/logs/:/var/log/mysql
    networks:
        - sp-net

networks:
  sp-net:
    external: true

